# App
spring.application.name=my-springboot-app
server.port=8080

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Enable Prometheus metrics endpoint
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
